/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MySharedComponent: typeof import('./src/components/MySharedComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_embla-carousel@8.6.0_typescript@5.8.3_vite@6.3.5_@t_87f4f0cb3081a09f40315924594b0a1b/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./src/components/UButton.vue')['default']
    UCard: typeof import('./src/components/UCard.vue')['default']
  }
}
